project:
  type: website
  output-dir: docs

website:
  title: "Data Science Blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/Iskanu93
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

execute:
  enabled: false